#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Thu May 23 09:58:07 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_fpga_top.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/ES7243E_reg_config.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/ES8156_reg_config.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/i2c_com.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/i2s_loop.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/pgr_i2s_rx.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/pgr_i2s_tx.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio/voice_loop.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/asyn_fifo.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/cordic_jpl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/cordic_newton.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/data_module_fft.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/fft_ctrl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/fft_top.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/fft_demo_00.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/distram_sdpram/ipsxe_fft_distram_sdpram.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/distram_sreg/ipsxe_fft_distram_sreg.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_sdpram_v1_2.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_shiftregister_v1_3.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_18k.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_36k.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/drm_sdpram/rtl/drm_init_param.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/drm_sdpram/rtl/ipml_sdpram_v1_7_drm.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/logos_fft_demo/rtl/synplify/ipsxe_fft_core_v1_1_vpAll.vp"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fir_paral/fir_guide.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fir_paral/mult_cell.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fir_paral/mult_man.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/dpram.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/hdmi_test1.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/iic_dri.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms72xx_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7200_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7210_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/pattern_vg_revised.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/hdmi_top/sync_vg_revised1.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/audio_data_pkt1_revised.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/crc32_d8.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/gmii_to_rgmii.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/udp_rx.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/udp_top.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/udp_top1.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/udp_top/udp_tx.v"
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/ipcore/pll/pll.idf
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/ipcore/ram2/ram2.idf
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/ipcore/fifo_audo_data_pkt/fifo_audo_data_pkt.idf
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/ipcore/PLL1/PLL1.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module audio_fpga_top
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/source/udp_top/audio_udp_top_pytest.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module audio_fpga_top
synthesize -ads -selected_syn_tool_opt 2 
remove_constraint  -logic -fdc "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/source/udp_top/audio_udp_top_pytest.fdc"
add_constraint "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_audio_fpga_top/source/src/audio_fpga_top.fdc"
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
