#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Fri May 17 15:57:39 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fir_paral/fir_guide.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fir_paral/mult_cell.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fir_paral/mult_man.v"
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fir_paral/tb_fir_guide.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fir_guide
synthesize -ads -selected_syn_tool_opt 2 
