# ----------------------------------------
# Created on: Sun May 19 14:15:42 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/pango_sim_libraries/pciegen2"
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/dpram.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/hdmi_test1.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/iic_dri.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms72xx_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7200_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7210_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/pattern_vg_revised.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/sync_vg_revised1.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/ipcore/ram2/rtl/ipm_distributed_sdpram_v1_2_ram2.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/ipcore/ram2/ram2.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/ipcore/pll/pll.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/tb_hdmi_test1.v" -work work

# ----------------------------------------
