# ----------------------------------------
# Created on: Sat May 18 11:29:12 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/pciegen2"
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/dpram.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/hdmi_test1.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/iic_dri.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms72xx_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7200_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7210_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/pattern_vg_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/sync_vg_revised1.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ipcore/ram2/rtl/ipm_distributed_sdpram_v1_2_ram2.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ipcore/ram2/ram2.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ipcore/pll/pll.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/sim/tb_hdmi_test1.v" -work work

# ----------------------------------------
