# ----------------------------------------
# Created on: Sat May 11 13:45:54 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/pciegen2"
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/hdmi_test_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/hdmi_top.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/iic_dri.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms72xx_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7200_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7210_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/pattern_vg_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/rw_ram_ctrl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/single_ram.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/sync_vg_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/prj/ipcore/pll/pll.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/tb_hdmi_top.v" -work work

# ----------------------------------------
