#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Jul 24 19:47:41 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/divide.v"
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/divide_tb.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module divide
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
