# ----------------------------------------
# Created on: Mon May 13 09:42:22 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_hdmi_test1/pciegen2"
vlog   "hdmi_test1_syn.vm" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/sim/tb_hdmi_test1.v" -work work

# ----------------------------------------
