# ----------------------------------------
# Created on: Fri Mar 29 16:09:36 2024
# Auto generated by Pango
# ----------------------------------------

# vsim  -novopt  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_fft_test usim.GTP_GRS
vsim -voptargs=+acc -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_fft_test usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
