# ----------------------------------------
# Created on: Sat May 18 09:46:01 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/fft_top/pango_datamodule_prj/pango_sim_libraries/pciegen2"
vlog   "C:/Users/86151/Desktop/auido_fft_fir/fft_top/src/cordic_jpl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/fft_top/src/cordic_newton.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/fft_top/src/data_module_fft.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/fft_top/sim/tb_data_module_fft.v" -work work

# ----------------------------------------
