#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sun May 19 10:17:03 2024

add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/asyn_fifo.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/fft_ctrl.v"
add_simulation "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/tb_fft_test.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/fft_test.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module fft_test
synthesize -ads -selected_syn_tool_opt 2 
