#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Mon Jul 22 15:23:38 2024

add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_hsst/ipcore/hsst_test/hsst_test.idf
