#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sat May  4 16:50:53 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/revised_new/audio_udp_pk2.v"
add_design C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/revised_new/prj_pk2/ipcore/fifo_audo_data_pkt/fifo_audo_data_pkt.idf
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
synthesize -ads -selected_syn_tool_opt 2 
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/revised_new/prj_pk2/tb_audio_data_pkt.v"
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_data_pkt2
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module audio_udp_pk2
synthesize -ads -selected_syn_tool_opt 2 
