#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Mon Apr 22 14:36:59 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/udp_re.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/udp_rx_re.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/udp_tx_re.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/arp/crc32_d8.v"
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/UDP/udp/tb_udp.v"
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module udp_re
synthesize -ads -selected_syn_tool_opt 2 
