# ----------------------------------------
# Created on: Mon Apr  1 11:11:22 2024
# Auto generated by Pango
# ----------------------------------------

vsim -voptargs=+acc -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_ipsxe_fft_core_only usim.GTP_GRS
# vsim  -novopt  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_ipsxe_fft_core_only usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
