# ----------------------------------------
# Created on: Mon Apr  1 11:12:35 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/prj/pango_sim_libraries/pciegen2"
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/fft_demo_00.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/pnr/core_only/ipsxe_fft_core_only.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/synplify/ipsxe_fft_core_v1_1_vpAll.vp" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_18k.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_36k.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/distram_sreg/ipsxe_fft_distram_sreg.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_sdpram_v1_2.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_shiftregister_v1_3.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/distram_sdpram/ipsxe_fft_distram_sdpram.v" -work work
vlog   "D:/fpga_competition/FPGA_competition/ziguangtongchuang_file/logos_fft_demo/rtl/drm_sdpram/rtl/ipml_sdpram_v1_7_drm.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/fft_design_form_pango/sim/tb_ipsxe_fft_core_only.v" -work work

# ----------------------------------------
