# ----------------------------------------
# Created on: Sun May 19 17:05:11 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_fir/pango_sim_libraries/pciegen2"
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fir_paral/fir_guide.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fir_paral/mult_cell.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fir_paral/mult_man.v" -work work
vlog   "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fir_paral/tb_fir_guide.v" -work work

# ----------------------------------------
