#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed May 22 15:25:03 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/DelayUnit.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/LMS.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/LMS_tap.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/lms_top.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/LMSX_selfdefine.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/LMSx8.v"
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_lms_top/ipcore/lms_fifo/lms_fifo.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/tb_lms_top.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_lms_top/ipcore/we/we.idf
add_design C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_lms_top/ipcore/lms_fifos/lms_fifos.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
remove_design -force C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/prj/prj_lms_top/ipcore/we/we.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module lms_top
synthesize -ads -selected_syn_tool_opt 2 
