#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sun May 19 10:44:05 2024

add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/cordic_jpl.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/cordic_newton.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/data_module_fft.v"
add_simulation "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/fft_top/tb_data_module_fft.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module cordic_newton
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module cordic_jpl
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
