#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sun May 19 11:13:46 2024

add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/dpram.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/hdmi_test1.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/hdmi_timing_sequence.h"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/iic_dri.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms72xx_ctl.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7200_ctl.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/ms7210_ctl.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/pattern_vg_revised.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/sync_vg_revised1.v"
add_design C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/ipcore/ram2/ram2.idf
add_design C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/prj/prj_hdmi/ipcore/pll/pll.idf
add_simulation "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/tb_hdmi_test1.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_design -verilog "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/hdmi_top/hdmi_timing_sequence.h"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_test1
synthesize -ads -selected_syn_tool_opt 2 
