# ----------------------------------------
# Created on: Wed Mar 27 15:48:38 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/src/fifo_test.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/ipcore/fifo1/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/ipcore/fifo1/rtl/ipml_sdpram_v1_6_fifo1.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/ipcore/fifo1/rtl/ipml_fifo_v1_6_fifo1.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/ipcore/fifo1/fifo1.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/pango_fifo_test/prj/fifo_test/sim/tb_fifo_test.v" -work work

# ----------------------------------------
