# ----------------------------------------
# Created on: Wed Mar 27 15:24:43 2024
# Auto generated by Pango
# ----------------------------------------
vsim -voptargs=+acc -L work tb_fifo_test
# vsim  -novopt  -L work tb_fifo_test
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
