#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sun May 19 17:52:02 2024

add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/lms/DelayUnit.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/lms/LMS.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/lms/LMS_tap.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/lms/LMSx8.v"
add_simulation "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/lms/LMS_sim.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
synthesize -ads -selected_syn_tool_opt 2 
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/lms/LMSX_selfdefine.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module LMS
synthesize -ads -selected_syn_tool_opt 2 
