# ----------------------------------------
# Created on: Thu May  9 20:04:53 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/pciegen2"
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/audio_fft_top.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/asyn_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/cordic_jpl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/data_module_fft.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/fft_ctrl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/fft_top.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/ipsxe_fft_exp_rom.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/pnr/core_only/ipsxe_fft_core_only.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/distram_sdpram/ipsxe_fft_distram_sdpram.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/distram_sreg/ipsxe_fft_distram_sreg.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_sdpram_v1_2.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/distram_sreg/rtl/ipsxe_fft_distributed_shiftregister_v1_3.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_18k.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/drm_sdpram/ipsxe_fft_drm_sdpram_36k.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/drm_sdpram/rtl/ipml_sdpram_v1_7_drm.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/synplify/ipsxe_fft_core_v1_1_vpAll.vp" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/fft_demo_00.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/logos_fft_demo/rtl/drm_sdpram/rtl/drm_init_param.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_fft_top/sim/tb_audio_fft_top.v" -work work

# ----------------------------------------
