# ----------------------------------------
# Created on: Wed Jun 12 18:03:31 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/fifo_ambition/prj/pango_sim_libraries/pciegen2"
vlog   "C:/Users/86151/Desktop/fifo_ambition/src/fifo_ambition.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition/rtl/ipm_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition/rtl/ipm_distributed_fifo_v1_2_fifo_ambition.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition/rtl/ipm_distributed_sdpram_v1_2_fifo_ambition.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition/fifo_ambition.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition_re/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition_re/rtl/ipml_sdpram_v1_6_fifo_ambition_re.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition_re/rtl/ipml_fifo_v1_6_fifo_ambition_re.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/prj/ipcore/fifo_ambition_re/fifo_ambition_re.v" -work work
vlog   "C:/Users/86151/Desktop/fifo_ambition/src/tb_fifo_ambition.v" -work work

# ----------------------------------------
