# ----------------------------------------
# Created on: Sun May 12 19:44:23 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/pciegen2"
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/fifo_ctrl_hdmi.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/hdmi_top_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/iic_dri.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms72xx_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7200_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/ms7210_ctl.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/sync_vg_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/hdmi_test_revised.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fft_top/asyn_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/pattern_vg_row.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_audio_hdmi_revised/ipcore/pll/pll.v" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/hdmi_top/src/tb_hdmi_top_revised.v" -work work

# ----------------------------------------
