webtalk_init -webtalk_dir C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/fft_top/fifo_test/fifo_test/fifo_test.sim/sim_1/behav/xsim/xsim.dir/tb_fifo_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 19 20:22:13 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fe10599c-3855-4f6e-a831-f29c8489dcdc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4a5ca677f3884ed6ae3b30f8175a7ecc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3933302602 -regid "" -xml C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/fft_top/fifo_test/fifo_test/fifo_test.sim/sim_1/behav/xsim/xsim.dir/tb_fifo_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/fft_top/fifo_test/fifo_test/fifo_test.sim/sim_1/behav/xsim/xsim.dir/tb_fifo_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/fft_top/fifo_test/fifo_test/fifo_test.sim/sim_1/behav/xsim/xsim.dir/tb_fifo_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
