#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Apr  3 15:49:25 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/hdmi_test.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/iic_dri.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms72xx_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7200_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7210_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/pattern_vg.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/sync_vg.v"
add_design C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/pango_hdmi_test/prj/ipcore/pll/pll.idf
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module hdmi_test
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module hdmi_test
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module hdmi_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms72xx_ctl.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/hdmi_test.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/sync_vg.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/pattern_vg.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7200_ctl.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7210_ctl.v"
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/iic_dri.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/hdmi_test.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/iic_dri.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms72xx_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7200_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/ms7210_ctl.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/pattern_vg.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/audio_fft_fir_hdmi/src/hdmi_top/src/sync_vg.v"
set_arch -family Logos -device PGL12G -speedgrade -5 -package FBG256
compile -top_module hdmi_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
