#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sun May 19 15:13:00 2024

add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/udp_top/crc32_d8.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/udp_top/udp_rx.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/udp_top/udp_top.v"
add_design "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/udp_top/udp_tx.v"
add_simulation "C:/Users/86151/Desktop/ziguangTongchuang_Competition_Documents/src/udp_top/tb_udp.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module udp_top
synthesize -ads -selected_syn_tool_opt 2 
