# ----------------------------------------
# Created on: Fri May 17 16:10:26 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/auido_fft_fir/audio_top/prj_file_test/prj_fir/pango_sim_libraries/pciegen2"
vlog   "fir_guide_syn.vm" -work work
vlog   "C:/Users/86151/Desktop/auido_fft_fir/audio_top/src/fir_paral/tb_fir_guide.v" -work work

# ----------------------------------------
