# ----------------------------------------
# Created on: Thu Jun 27 10:39:12 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/usim"
vmap  adc "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/86151/Desktop/ddr3_test1/prj/pango_sim_libraries/pciegen2"
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/axi_m_revised.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/axi_m_top.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/ddr3_test.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/led_disp.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/rw_fifo_ctrl.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/ddr_data_inandout.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/axi_m.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/ddr_test.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/ddr_test_ddrphy_top.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ipsxb_rst_sync_v1_1.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_calib_mux_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_calib_top_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_control_path_adj_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_v1_4.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_dqs_gate_cal_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_wrlvl_v1_4.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dfi_v1_4.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dll_update_ctrl_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqsi_rdel_cal_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqs_gate_coarse_cal_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqs_rddata_align_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_drift_ctrl_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_gate_update_ctrl_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_gatecal_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_info_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_init_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_main_ctrl_v1_3.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_rdcal_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_reset_ctrl_v1_4.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_rst_debounce_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_slice_rddata_align_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_training_ctrl_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_upcal_v1_4.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_wdata_path_adj_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_wrlvl_v1_0.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_slice_top_v1_4.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/pll/ipsxb_ddrphy_pll_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_apb_cross_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_calib_delay_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_cfg_apb_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_bm_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_rowaddr_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_sm_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_top_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_back_ctrl_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_buf_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_out_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_top_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dfi_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_lp_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_mrs_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_prefetch_fifo_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_rdatapath_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_reg_fifo2_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_ui_axi_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdatapath_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_align_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_dcp_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wrapper_v1_2a.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_com_timing_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_timing_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act2wr_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_pre_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_rd_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_ref_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_wr_pass_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_trc_timing_v1_2.vp" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/ipsxb_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_ctr_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_sdpram_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/write_ddr_fifo/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/write_ddr_fifo/rtl/ipml_sdpram_v1_6_write_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/write_ddr_fifo/rtl/ipml_fifo_v1_6_write_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/write_ddr_fifo/write_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/read_ddr_fifo/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/read_ddr_fifo/rtl/ipml_sdpram_v1_6_read_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/read_ddr_fifo/rtl/ipml_fifo_v1_6_read_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/prj/ipcore/read_ddr_fifo/read_ddr_fifo.v" -work work
vlog   "C:/Users/86151/Desktop/ddr3_test1/src/ddr_sim.v" -work work

# ----------------------------------------
