#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Sat Jul 20 10:56:34 2024

add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/auido_recognization.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/divide.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/fft_top/cordic_newton.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_simulation "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/auido_recognization_tb.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_design -verilog "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/auido_recognization.v"
add_design "C:/Users/86151/Desktop/auido_fft_fir/ziguangTongchuang_Competition_Documents/src/audio_recognization/auido_recognization.sv"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module auido_recognization
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
